### ISSUE TITLE
License is wrong

### ISSUE THREAD

**Issue by hmarthinsen** [nmatt11/Rootedtrees#1]
Copied from my comment on Stack Exchange:

You are free to make your own version of my package, but it must be licensed under GPL version 3 (or newer), not version 2 as you have done. Also, please retain the license notices as well as the Authors information in the top of the Python source file. You may add your own name to the Authors list.

**Comment by nmatt11** [comment]
I believe that the issues pointed out should now be solved.

**Comment by hmarthinsen** [comment]
Everything looks OK now. :+1:
